apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: szn-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: szn-test
  template:
    metadata:
      labels:
        app: szn-test
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: 8090
              protocol: TCP
          resources:
          {{- range $key, $value := $.Values.App.Resources }}
            {{ $key }}:
              {{ toYaml $value }}
          {{- end }}
